version: '3.8'

services:
  database:
    build: ./database
    container_name: stock_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: stocks
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: stock_backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: stocks
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: stock_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  db_data: